// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARxUOMJ1KS-_AhP6rQiCZR963FxZ2MS6g',
    appId: '1:724916384275:web:136392a7c8c307d57d05e6',
    messagingSenderId: '724916384275',
    projectId: 'assignment-5-aab80',
    authDomain: 'assignment-5-aab80.firebaseapp.com',
    storageBucket: 'assignment-5-aab80.appspot.com',
    measurementId: 'G-DKX048TQJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYnAglxp7Kd8aTKLkfirC7KHd3dctwwxg',
    appId: '1:724916384275:android:4208cc141133f6857d05e6',
    messagingSenderId: '724916384275',
    projectId: 'assignment-5-aab80',
    storageBucket: 'assignment-5-aab80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7JfEJC-cDlzILADyvd6pNkejIOAShCTQ',
    appId: '1:724916384275:ios:0b262e129887903a7d05e6',
    messagingSenderId: '724916384275',
    projectId: 'assignment-5-aab80',
    storageBucket: 'assignment-5-aab80.appspot.com',
    iosBundleId: 'com.example.assignment5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7JfEJC-cDlzILADyvd6pNkejIOAShCTQ',
    appId: '1:724916384275:ios:e819fa3276ef309a7d05e6',
    messagingSenderId: '724916384275',
    projectId: 'assignment-5-aab80',
    storageBucket: 'assignment-5-aab80.appspot.com',
    iosBundleId: 'com.example.assignment5.RunnerTests',
  );
}
